schema_version: 1

context:
  version: "3.1.1"

package:
  name: tango-takeoff
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tango-takeoff/tango_takeoff-${{ version }}.tar.gz
  sha256: 7ade4c136f5a19534a41dc5b23b344a5e1300cba134cb428f929d831661dca3d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - takeoff = takeoff.runner:run

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - pytango

tests:
  - python:
      imports:
        - takeoff
        - takeoff.runner
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - takeoff --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: A script that can find, start and stop Tango Device Server(s)
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/MaxIV/tools/tango-takeoff
  repository: https://gitlab.com/MaxIV/tools/tango-takeoff

extra:
  recipe-maintainers:
    - beenje
